#!/bin/sh

# Extracts a ParamChem-compatible c_file and e_file from a Q-Chem output
# file. Run without command-line arguments for usage information.

# Copyright (C) 2014 Kenno Vanommeslaeghe
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $# -lt 1 ] ; then
  echo "Usage: `basename $0` <q-chem output file>
       `basename $0` <prefix for .c_file and .e_file> <q-chem output file>...

If only one argument is given, the prefix will be based on the log file name.
If 2 or more arguments are given, the first argument is taken as a prefix.
In the latter case, output files will be overwritten without prompting!

WARNING! This is version 0 and *only* does RIMP2 single points!!!" >&2
# A more fully featured version should be constructed based on scan2cat_gauss
  exit 1
 fi
if [ $# = 1 ] ; then
  prefix=${1##*/}
  prefix=${prefix%.*}
  if [ -e "$prefix.e_file" -o -e "$prefix.c_file" ] ; then
    echo "ERROR: output file already exists!" >&2
    exit 1
  fi
 else
  prefix=$1
  shift 1
 fi

awk -v pre="$prefix" 'BEGIN {stage=2;efn=pre ".e_file";cfn=pre ".c_file"}
    (stage == 3){if (NF == 5) printf("%9.5f %9.5f %9.5f\n",$3,$4,$5) > cfn
       else if ($1 ~ "^----------------------------------------------------") stage=2
       else {err=1;exit 1} }
    (stage == 2){if ($0 ~ "Standard Nuclear Orientation \\(Angstroms\\)") {
        getline;getline;stage=3}
       else if ($1 == "RIMP2" && $2 == "total") printf("%-18.4f\n",$5 * 627.509471) > efn}
    END{if (err || stage != 2) {
      print "ERROR: invalid or unrecognized Q-chem output!" > "/dev/stderr"
      exit 1} }' $*
